name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Set up test database
      run: |
        echo "MONGO_TEST_URL=mongodb://localhost:27017/trivia-app-test" >> .env
        npm run fixtures

    - name: Run tests
      run: npm test